import os
import rtconfig
from building import *

cwd = GetCurrentDir()
path =  [cwd]
group = []

# add general drivers
src = Split('''
board.c
startup_stm32f103xb.s
''')

# STM32F100xB || STM32F100xE || STM32F101x6
# STM32F101xB || STM32F101xE || STM32F101xG
# STM32F102x6 || STM32F102xB || STM32F103x6
# STM32F103xB || STM32F103xE || STM32F103xG
# STM32F105xC || STM32F107xC)
# You can select chips from the list above
CPPDEFINES = ['STM32F103xB']
group = group + SConscript(os.path.join(cwd, 'stm_sdk', 'SConscript'))
group = group + DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
